# Используем базовый образ Ubuntu
FROM ubuntu:latest

# Обновляем систему
RUN apt-get update && apt-get upgrade -y

# Устанавливаем Nginx
RUN apt-get install -y nginx

# Удаляем кеш APT и временные файлы
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Копируем файлы сайта
COPY site /var/www/html

# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]
